### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by solkimicreb** [emartech/boar-ng-common#1]
Hi!

Are there any plans for supporting angular 2+? We have to rewrite the mobile engagement screen with angular 5 and we couldn't find anything to replace the angular 1 boar stack.

Thanks 🙂

**Comment by judge** [comment]
Hi!
Sorry but this is for AngularJS, we don't plan to support Angular2+ with boar components, you should use UI components from the ui framework of Emarsys.
